---
# handlers file for firewall
- name: reload firewall
  service:
    name: "{{ firewall_service }}"
    state: reloaded
  when:
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "container"

- name: reload firewalld
  command: firewall-cmd --reload
